return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.4",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 32,
  tilewidth = 10,
  tileheight = 10,
  nextlayerid = 11,
  nextobjectid = 49,
  properties = {
    ["music"] = "mus/submenu.vgm",
    ["prevmap"] = "mainmenu.lua",
    ["script"] = "MenuMap"
  },
  tilesets = {
    {
      name = "bg_swirl",
      firstgid = 1,
      filename = "img/bg_swirl.tsx",
      tilewidth = 10,
      tileheight = 10,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "img/bg_swirl.png",
      imagewidth = 50,
      imageheight = 50,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 5,
        height = 5
      },
      properties = {},
      terrains = {},
      tilecount = 25,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 9,
      name = "Tile Layer 1",
      x = 0,
      y = 0,
      width = 24,
      height = 32,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["script"] = "InfiniteScrollLayer",
        ["scrolling"] = true,
        ["scrollvelx"] = 60,
        ["scrollvely"] = 60,
        ["tilewrap"] = true
      },
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0TcSgEAQA8HDew5v/v9RJl7CLYikqk6UTgj/LEGKDDkK52dXokKNBq3zs+vQY8CI6PzsJsxYsGJzfnY7Dpy4cDs/O/VVX/VVX/VVX/V9T33V19P3qz1GYh55"
    },
    {
      type = "objectgroup",
      id = 2,
      name = "Object Layer 3",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 4,
          name = "camera",
          type = "Camera",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 240,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 3,
      name = "options_pc",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["script"] = "MenuPrefs"
      },
      objects = {
        {
          id = 2,
          name = "cancel",
          type = "UIButton",
          shape = "text",
          x = 30,
          y = 264,
          width = 180,
          height = 20,
          rotation = 0,
          visible = false,
          text = "cancel",
          fontfamily = "Press Start 2P",
          pixelsize = 8,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 1,
          name = "fullscreen",
          type = "UIBoolean",
          shape = "text",
          x = 30,
          y = 20,
          width = 180,
          height = 20,
          rotation = 0,
          visible = false,
          text = "fullscreen",
          fontfamily = "Press Start 2P",
          pixelsize = 8,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 3,
          name = "vsync",
          type = "UIBoolean",
          shape = "text",
          x = 30,
          y = 40,
          width = 180,
          height = 20,
          rotation = 0,
          visible = false,
          text = "vsync",
          fontfamily = "Press Start 2P",
          pixelsize = 8,
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 5,
          name = "volume",
          type = "UIOption",
          shape = "text",
          x = 20,
          y = 200,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Volume ${volume}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["increment"] = 0.25,
            ["max"] = 1,
            ["units"] = "percent"
          }
        },
        {
          id = 6,
          name = "canvasscale",
          type = "UIOption",
          shape = "text",
          x = 20,
          y = 110,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Max pixel scale ${canvasscale}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["increment"] = 1,
            ["max"] = 6,
            ["min"] = 1
          }
        },
        {
          id = 9,
          name = "rotation",
          type = "UIOption",
          shape = "text",
          x = 20,
          y = 170,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Rotation (cw) ${rotation}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["increment"] = 90,
            ["max"] = 270,
            ["min"] = 0
          }
        },
        {
          id = 7,
          name = "back",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 280,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Back",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "goBack"
          }
        },
        {
          id = 8,
          name = "default",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 260,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Reset defaults",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "resetPrefs"
          }
        },
        {
          id = 19,
          name = "controller",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 80,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Controller",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "changeMenu",
            ["nextmenu"] = "options_controller"
          }
        },
        {
          id = 20,
          name = "keyboard",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 60,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Keyboard",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "changeMenu",
            ["nextmenu"] = "options_keyboard"
          }
        },
        {
          id = 32,
          name = "menutitle",
          type = "",
          shape = "text",
          x = 30,
          y = 20,
          width = 180,
          height = 20,
          rotation = 0,
          visible = true,
          text = "OPTIONS",
          fontfamily = "Lady Radical",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 44,
          name = "canvasscaleint",
          type = "UIBoolean",
          shape = "text",
          x = 20,
          y = 130,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Integer scale ${canvasscaleint}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 45,
          name = "canvasscalesoft",
          type = "UIBoolean",
          shape = "text",
          x = 20,
          y = 150,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Soft scale ${canvasscalesoft}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 4,
      name = "options_mobile",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["script"] = "MenuPrefs"
      },
      objects = {
        {
          id = 35,
          name = "menutitle",
          type = "",
          shape = "text",
          x = 30,
          y = 20,
          width = 180,
          height = 20,
          rotation = 0,
          visible = true,
          text = "OPTIONS",
          fontfamily = "Lady Radical",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 36,
          name = "default",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 260,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Reset defaults",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "resetPrefs"
          }
        },
        {
          id = 37,
          name = "back",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 280,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Back",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "goBack"
          }
        },
        {
          id = 38,
          name = "canvasscale",
          type = "UIOption",
          shape = "text",
          x = 20,
          y = 110,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Max pixel scale ${canvasscale}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["increment"] = 1,
            ["max"] = 6,
            ["min"] = 1
          }
        },
        {
          id = 39,
          name = "volume",
          type = "UIOption",
          shape = "text",
          x = 20,
          y = 200,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Volume ${volume}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["increment"] = 0.25,
            ["max"] = 1,
            ["units"] = "percent"
          }
        },
        {
          id = 42,
          name = "controller",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 80,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Controller",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "changeMenu",
            ["nextmenu"] = "options_controller"
          }
        },
        {
          id = 46,
          name = "canvasscaleint",
          type = "UIBoolean",
          shape = "text",
          x = 20,
          y = 130,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Integer scale ${canvasscaleint}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 47,
          name = "canvasscalesoft",
          type = "UIBoolean",
          shape = "text",
          x = 20,
          y = 150,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Soft scale ${canvasscalesoft}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 5,
      name = "options_keyboard",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["prevmenu"] = "options_pc",
        ["script"] = "UIMenu"
      },
      objects = {
        {
          id = 10,
          name = "key_left",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 60,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Left = ${key_left}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 11,
          name = "key_right",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 80,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Right = ${key_right}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 12,
          name = "key_up",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 100,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Up = ${key_up}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 13,
          name = "key_down",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 120,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Down = ${key_down}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 14,
          name = "key_fire",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 140,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Fire = ${key_fire}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 15,
          name = "key_focus",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 160,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Alt Fire = ${key_focus}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 16,
          name = "key_bomb",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 180,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Bomb = ${key_bomb}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 17,
          name = "key_pausemenu",
          type = "",
          shape = "text",
          x = 20,
          y = 200,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Pause = ${key_pausemenu}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 21,
          name = "key_pause",
          type = "UIInputBind",
          shape = "text",
          x = 30,
          y = 180,
          width = 180,
          height = 15,
          rotation = 0,
          visible = false,
          text = "pause",
          fontfamily = "Press Start 2P",
          pixelsize = 8,
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {}
        },
        {
          id = 18,
          name = "back",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 280,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Back",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "goBack"
          }
        },
        {
          id = 33,
          name = "menutitle",
          type = "",
          shape = "text",
          x = 30,
          y = 20,
          width = 180,
          height = 20,
          rotation = 0,
          visible = true,
          text = "KEYBOARD",
          fontfamily = "Lady Radical",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 6,
      name = "options_controller",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["prevmenu"] = "options_pc",
        ["script"] = "UIMenu"
      },
      objects = {
        {
          id = 24,
          name = "joy_x",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 100,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Move⟷ = ${joy_x}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["inputtype"] = "axis"
          }
        },
        {
          id = 25,
          name = "joy_y",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 120,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Move↕  = ${joy_y}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["inputtype"] = "axis"
          }
        },
        {
          id = 26,
          name = "joy_fire",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 140,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Fire = ${joy_fire}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["inputtype"] = "button"
          }
        },
        {
          id = 27,
          name = "joy_focus",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 160,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Alt Fire = ${joy_focus}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["inputtype"] = "button"
          }
        },
        {
          id = 28,
          name = "joy_bomb",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 180,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Bomb = ${joy_bomb}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["inputtype"] = "button"
          }
        },
        {
          id = 29,
          name = "joy_pausemenu",
          type = "UIInputBind",
          shape = "text",
          x = 20,
          y = 200,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Pause = ${joy_pausemenu}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["inputtype"] = "button"
          }
        },
        {
          id = 30,
          name = "back",
          type = "UIButton",
          shape = "text",
          x = 20,
          y = 280,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Back",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {
            ["action"] = "goBack"
          }
        },
        {
          id = 34,
          name = "menutitle",
          type = "",
          shape = "text",
          x = 30,
          y = 20,
          width = 180,
          height = 20,
          rotation = 0,
          visible = true,
          text = "CONTROLLER",
          fontfamily = "Lady Radical",
          wrap = true,
          color = { 255, 255, 255 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 48,
          name = "joy_namingscheme",
          type = "UIOption",
          shape = "text",
          x = 20,
          y = 60,
          width = 200,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Controller Type = ${joy_namingscheme}",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          valign = "center",
          properties = {
            ["max"] = 4,
            ["min"] = 1,
            ["valuestr1"] = "XBOX",
            ["valuestr2"] = "PS4",
            ["valuestr3"] = "PS3",
            ["valuestr4"] = "SWITCH",
            ["valuestr5"] = "OTHER"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 7,
      name = "inputbind_instructions",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 40,
          name = "",
          type = "",
          shape = "text",
          x = 20,
          y = 220,
          width = 200,
          height = 60,
          rotation = 0,
          visible = true,
          text = "Press new %s to assign, or ${key_pausemenu} or ${joy_pause} to cancel",
          fontfamily = "Unifont",
          wrap = true,
          color = { 255, 255, 255 },
          properties = {
            ["textformat"] = "Press new %s to assign, or Escape or ${joy_pause} to cancel"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "curtain",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["script"] = "Curtain"
      },
      objects = {}
    }
  }
}
