# LOVE Multiplatform GitLab CI

# Fill in the project info
variables:
        PROJECT: demonizer
        PROJECT_TITLE: Demonizer
        PROJECT_TITLE_NOSPACE: Demonizer
        DESCRIPTION: "Demonic corruption fantasy shmup"
        COPYRIGHT: "© 2020 IoriBranford"
        APPLICATION_ID_BASE: "io.itch.ioribranford.demonizer"
        LOVE_VERSION: "11.3"
        SCREEN_ORIENTATION: "sensorPortrait"
        GAME_TYPE: full
        VERSION: "${CI_COMMIT_REF_NAME}"
        GIT_DEPTH: "1"
        GIT_SUBMODULE_STRATEGY: recursive

# Fill in the demo info if providing a demo
.demo:
        <<: &demo
                only:
                        - master
                        - /demo/
        variables:
                <<: &demo-variables
                        PROJECT_TITLE: "Demonizer Demo"
                        PROJECT_TITLE_NOSPACE: "Demonizer_Demo"
                        GAME_TYPE: demo

.full:
        <<: &full
                except:
                        - /demo/

stages:
        - build

image: alpine:latest

before_script:
        - apk add --update git zip luajit

.debian:
        <<: &debian
                before_script:
                        - apt-get update
                        - apt-get install -y -qq git zip luajit

.build-data: &build-data
        stage: build
        script:
                - apk add wget xz
                - ./make-game.sh
        artifacts:
                name: "${PROJECT}-${VERSION}-data"
                paths:
                        - "${GAME_ASSET}"

.build-linux: &build-linux
        <<: *debian
        stage: build
        image: debian:stretch-slim
        script:
                - apt-get install -y -qq file wget fuse libglib2.0-0
                - ./make-linux.sh
        cache:
                key: "${PROJECT}-linux-${ARCH}"
                paths:
                        - "love-${LOVE_VERSION}-${ARCH}.AppImage"
                        - "appimagetool"
                        - "*.deb"
        artifacts:
                name: "${PROJECT}-${VERSION}-linux-${ARCH}"
                paths:
                        - ${PROJECT_TITLE_NOSPACE}-${ARCH}.AppImage

.build-windows: &build-windows
        <<: *debian
        image: tianon/wine
        stage: build
        variables:
                ARCH_BITS: "64"
                GAME_DIR: "${PROJECT_TITLE}"
                ICO: "appicon.ico"
        script:
                - apt-get install -y -qq wget
                - ./make-windows.sh
        cache:
                key: "${PROJECT}-win-${ARCH_BITS}"
                paths:
                        - "love-${LOVE_VERSION}-win${ARCH_BITS}"
                        - "bin"
                        - "rcedit-x64.exe"
        artifacts:
                name: "${PROJECT}-${VERSION}-win-${ARCH_BITS}"
                paths:
                        - "${PROJECT_TITLE}"

.build-dev-windows: &build-dev-windows
        stage: build
        variables:
                ARCH_BITS: "64"
        script:
                - apk add wget
                - ./make-dev-windows.sh
        cache:
                key: "${PROJECT}-win-${ARCH_BITS}"
                paths:
                        - "love-${LOVE_VERSION}-win${ARCH_BITS}"
                        - "bin"
        artifacts:
                name: "${PROJECT}-dev-win-${ARCH_BITS}"
                paths:
                        - "${PROJECT_TITLE}"

.build-osx: &build-osx
        <<: *debian
        stage: build
        image: fzwoch/osxcross
        variables:
                CFBundleIdentifier: "${APPLICATION_ID_BASE}"
                <<: &build-osx-variables
                        NSHumanReadableCopyright: "${COPYRIGHT}"
                        INSTALL_NAME_TOOL: x86_64-apple-darwin12-install_name_tool
        script:
                - apt-get install -y -qq wget
                - ./make-macosx.sh
        cache:
                key: "${PROJECT}-osx"
                paths:
                        - "love.app"
                        - "game-music-emu"
        artifacts:
                name: "${PROJECT}-${VERSION}-osx"
                paths:
                        - "${PROJECT_TITLE}.app"

.build-android: &build-android
        <<: *debian
        stage: build
        image: lakoo/android-ndk:28-28.0.3-r19c
        variables:
                APPLICATION_ID: "${APPLICATION_ID_BASE}"
                GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
        script:
                - apt-get install -y -qq make file
                - ./make-android.sh
        cache:
                key: "${PROJECT}-android"
                paths:
                        - love-apk-src
                        - apktool.jar
                        - uber-apk-signer.jar
                        - apktool
                        - .gradle
        artifacts:
                name: "${PROJECT}-${VERSION}-android"
                paths:
                        - "${PROJECT_TITLE_NOSPACE}.apk"

data:
        variables:
                GAME_ASSET: "${PROJECT}-${GAME_TYPE}.love"
        <<: *build-data
        <<: *full

linux-x86_64:
        <<: *build-linux
        <<: *full
        variables:
                ARCH: "x86_64"

linux-i686:
        <<: *build-linux
        <<: *full
        image: i386/debian:stretch-slim
        variables:
                ARCH: "i686"

win-64:
        <<: *build-windows
        <<: *full

win-32:
        <<: *build-windows
        <<: *full
        variables:
                ARCH_BITS: "32"

osx:
        <<: *build-osx
        <<: *full

android:
        <<: *build-android
        <<: *full

demo-data:
        variables:
                <<: *demo-variables
                GAME_ASSET: "${PROJECT}-${GAME_TYPE}.love"
        <<: *build-data
        <<: *demo

demo-linux-x86_64:
        <<: *build-linux
        <<: *demo
        variables:
                ARCH: "x86_64"
                <<: *demo-variables

demo-linux-i686:
        <<: *build-linux
        <<: *demo
        image: i386/debian:stretch-slim
        variables:
                ARCH: "i686"
                <<: *demo-variables

demo-win-64:
        <<: *build-windows
        <<: *demo
        variables:
                <<: *demo-variables
                ARCH_BITS: "64"

demo-win-32:
        <<: *build-windows
        <<: *demo
        variables:
                <<: *demo-variables
                ARCH_BITS: "32"

demo-osx:
        <<: *build-osx
        <<: *demo
        variables:
                <<: *demo-variables
                <<: *build-osx-variables
                CFBundleIdentifier: "${APPLICATION_ID_BASE}demo"

demo-android:
        <<: *build-android
        <<: *demo
        variables:
                <<: *demo-variables
                APPLICATION_ID: "${APPLICATION_ID_BASE}demo"

dev-win-64:
        <<: *build-dev-windows
        <<: *full

dev-win-32:
        <<: *build-dev-windows
        <<: *full
        variables:
                ARCH_BITS: "32"
