language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17

env:
        global:
                - GAME_DIR=$TRAVIS_BUILD_DIR/game
                - GAME_ASSET=game.love
                - ANDROID_NDK_HOME=$HOME/android-ndk
                - PATH=$ANDROID_NDK_HOME:$PATH
                - LOVE_ANDROID_DIR=$TRAVIS_BUILD_DIR/love-android-sdl2
                - LOVE_ANDROID_ASSETS_DIR=$LOVE_ANDROID_DIR/assets

git:
        depth: 1

before_install:
        - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        - sudo apt-get install -y git-lfs

install:
        - git lfs pull
        - git clone https://github.com/urho3d/android-ndk.git $ANDROID_NDK_HOME

before_script:
        - cd $GAME_DIR
        - find -name "*.lua" | zip $GAME_ASSET -@
        - find -name "*.png" | zip $GAME_ASSET -@
        - find -name "*.vgm" | zip $GAME_ASSET -@
        - find -name "*.wav" | zip $GAME_ASSET -@
        - find -name "*.fnt" | zip $GAME_ASSET -@
        - find -name "*.txt" | zip $GAME_ASSET -@
        - cd $TRAVIS_BUILD_DIR

        - cp -r $TRAVIS_BUILD_DIR/love-android/* $LOVE_ANDROID_DIR
        - mkdir $LOVE_ANDROID_ASSETS_DIR
        - cp $GAME_DIR/$GAME_ASSET $LOVE_ANDROID_ASSETS_DIR
        - cd $LOVE_ANDROID_DIR
        - ndk-build

script:
        - ant debug
